steps:
    - id: "Building go modules"
      name: 'golang'
      env:
        - GOPATH=/gopath
        - GO111MODULE=on
        - GOPROXY=https://proxy.golang.org
      dir: desafio-go
      args: 
        - go
        - build
        - ./5_Utilizando_k8s/desafio-go/
        - desafio-go
      volumes:
        - name: go-modules
          path: /gopath

    - id: "Performing Go Test"
      name: 'golang'
      env:
        - GOPATH=/gopath
        - GO111MODULE=on
        - GOPROXY=https://proxy.golang.org
      dir: desafio-go
      volumes:
        - name: go-modules
          path: /gopath
      args:
        - go
        - test
        - ./5_Utilizando_k8s/desafio-go/
        - desafio-go

    - id: "Performing go application"
      name: 'docker'
      args: ["run", "16121988/utilizando-k8s"]
