steps:
    - id: "Performing Go Test"
      name: 'golang'
      args: ["go", "test", "./5_Utilizando_k8s/desafio-go/"]

    - id: "Performing go application"
      name: 'docker'
      args: ["run", "16121988/utilizando-k8s"]
