apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-configmap
data:
    nginx-conf-key: |

        <!DOCTYPE html>
        <html>
            <head>
                <meta charset="utf-8" />
                <title>Learning Kubernetes</title>
            </head>
            <body>
                <h1>Code.education Rocks</h1>
            </body>
        </html> 