apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deployment
    labels:
        app: nginx-deployment-utilizando-k8s
spec:
    replicas: 3
    selector:
        matchLabels:
            app: nginx-utilizando-k8s
    template:
        metadata:
            labels:
                app: nginx-utilizando-k8s
        spec:
            containers:
                - name: nginx
                  image: nginx:1.19.3-alpine
                  ports:
                    - containerPort: 80
                  
                  volumeMounts:
                    - mountPath: /usr/share/nginx/html
                      name: nginx-conf-volume
                      readOnly: false


            volumes:
                - name: nginx-conf-volume
                  configMap:
                    name: nginx-configmap
                    items:
                        - key: nginx-conf-key
                          path: index.html


