apiVersion: v1
kind: Service
metadata:
    name: nginx-service
    labels:
        app: nginx-service-utilizando-k8s
spec:
    type: LoadBalancer
    ports:
        - port: 80
          protocol: TCP
    selector:
        app: nginx-utilizando-k8s