apiVersion: apps/v1
kind: Deployment
metadata:
    name: go-hpa
    labels:
        app: go-hpa-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: go-hpa
    template:
        metadata:
            labels:
                app: go-hpa
        spec:
            containers:
                - name: go-hpa
                  image: go-image-deploy
                  ports:
                    - containerPort: 8000
                  resources:
                    limits:
                        cpu: 100m
                    requests:
                        cpu: 50m