steps:
    #   name: 'gcr.io/$PROJECT_ID/image_name'
    - id: "Performing Go Test"
      name: 'golang'
      args: ["go", "test", "./4_Desafio_de_CI/src/"]

    - id: "Performing Go Run"
      name: 'golang'
      args: ["go", "run", "./4_Desafio_de_CI/src/main.go"]