steps:
    - id: "Performing Go Test"
      name: 'golang'
      args: ["go", "test", "./4_Desafio_de_CI/src/"]

    - id: "Creating golang app image"
      name: 'docker'
      args: ["build", "-t", "gcr.io/$PROJECT_ID/desafio-ci:latest", "./4_Desafio_de_CI/"]

    - id: "Performing application"
      name: 'docker'
      args: ["run", "gcr.io/$PROJECT_ID/desafio-ci:latest"]

images:
    - "gcr.io/$PROJECT_ID/desafio-ci:latest"
