apiVersion: v1
kind: Service
metadata:
    name: go-hpa
    labels:
        app: go-hpa-service
spec:
    type: LoadBalancer
    ports:
        - port: 8000
          protocol: TCP
    selector:
        app: go-hpa