apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-deployment
    labels:
        app: mysql-deployment-utilizando-k8s
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql-server
            tier: database
    template:
        metadata:
            labels:
                app: mysql-server
                tier: database
        spec:
            containers:
                - name: mysql
                  image: mysql:8.0
                  ports:
                    - containerPort: 3306
                  env:
                    - name: MYSQL_ROOT_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: mysql-password
                            key: password

                  volumeMounts:
                    - name: mysql-persistent-volume-claim
                      mountPath: /var/lib/mysql
            
            volumes:
                - name: mysql-persistent-volume-claim
                  persistentVolumeClaim:
                    claimName: mysql-pvc