apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-pvc
    labels:
        app: mysql-pvc-utilizando-k8s
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 20Gi