apiVersion: v1
kind: Service
metadata:
    name: desafio-go-service
    labels:
        app: desafio-go-service-utilizando-k8s
spec:
    type: LoadBalancer
    ports:
        - port: 8000
          protocol: TCP
    selector:
        app: desafio-go-utilizando-k8s