steps:
    - id: "Building go modules"
      name: 'golang'
      env:
        - GOPATH=/gopath
        - GO111MODULE=on
        - GOPROXY=https://proxy.golang.org
      dir: ./7_deploy_continuo/
      args: 
        - go
        - build
      volumes:
        - name: go-modules
          path: /gopath

    - id: "Performing Go Test"
      name: 'golang'
      env:
        - GOPATH=/gopath
        - GO111MODULE=on
        - GOPROXY=https://proxy.golang.org
      dir: ./7_deploy_continuo/
      args:
        - go
        - test
      volumes:
        - name: go-modules
          path: /gopath

    - id: "Building go docker image"
      name: 'docker'
      args: ["build", "-t", "gcr.io/$PROJECT_ID/go-deploy-continuo:$SHORT_SHA", "./7_deploy_continuo/"]
    
    - id: "Pushing go docker image"
      name: 'docker'
      args: ["push", "gcr.io/$PROJECT_ID/go-deploy-continuo:$SHORT_SHA"]

    - id: "Changing image in kubernetes deployment"
      name: 'gcloud'
      # name: gcr.io/cloud-builders/gcloud
      entrypoint: '/bin/sh'
      args:
        - '-c'
        - |
          sed 's#go-image-deploy#gcr.io/$PROJECT_ID/go-deploy-continuo:$SHORT_SHA#g' ./7_deploy_continuo/k8s/deployment.yml > ./7_deploy_continuo/k8s/deployment-new.yml;
          cat ./7_deploy_continuo/k8s/deployment-new.yml;
    
    # - id: "Deploying kubernetes"
    #   name: 'kubectl'
    #   # name: gcr.io/cloud-builders/kubectl
    #   args:
    #     - 'apply'
    #     - '-f'
    #     - ./7_deploy_continuo/k8s/deployment-new.yml
    #   env:
    #     - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    #     - 'CLOUD_CONTAINER_CLUSTER=name_my_cluster'