steps:
    - id: "Building go modules"
      name: 'golang'
      env:
        - GOPATH=/gopath
        - GO111MODULE=on
        - GOPROXY=https://proxy.golang.org
      dir: ./7_deploy_continuo/
      args: 
        - go
        - build
      volumes:
        - name: go-modules
          path: /gopath

    - id: "Performing Go Test"
      name: 'golang'
      env:
        - GOPATH=/gopath
        - GO111MODULE=on
        - GOPROXY=https://proxy.golang.org
      dir: ./7_deploy_continuo/
      args:
        - go
        - test
      volumes:
        - name: go-modules
          path: /gopath

    - id: "Performing go application"
      name: 'docker'
      args: ["pull", "16121988/go-hpa"]
